name: mycustompipeline

on:
  push:
    branches: [ main ]

jobs:
  setup-install:
   runs-on: ip-172-31-37-84
   steps:
   - name: Checkout code
     uses: actions/checkout@v6

   - name: Set up Java
     uses: actions/setup-java@v3
     with:
      distribution: 'temurin'
      java-version: '11'
