name: mycustompipeline

on:
  push:
    branches: [ main ]

jobs:
  setup-install:
   runs-on: mynewrunner
   steps:
   - name: Checkout code
     uses: actions/checkout@v6

   - name: Set up Java
     uses: actions/setup-java@v3
     with:
      distribution: 'temurin'
      java-version: '11'

   - name: Set up Maven
     run: sudo apt install maven -y
 
  Test:
    runs-on: mynewrunner
    needs: setup-install
    steps:
    - name: unit test
      run: mvn test
